### ISSUE TITLE
Can you add the hashtag hackoctoberfest to the repo?

### ISSUE THREAD

**Issue by kasuken** [mjtpena/CloudIcons#1]
I would like to contribute to the repo, can you add the official hashtag?
thanks

**Comment by mjtpena** [comment]
Sorry I'm not familiar with hackoctoberfest. How do I do that? Btw I added it on readme, not sure if that's how to do it?

**Comment by kasuken** [comment]
under the repository description, you can add it in the topics #Hacktoberfest

**Comment by mjtpena** [comment]
Got it
